### PR TITLE
Fix: Typos in NEAR Docs

### PR DESCRIPTION
**Pull request by jennifer-notifi**
- Correct setState function and variables names
- Pass in the correct signMessage function
- Add comment on assumption to have `NEARWalletContextProvider` set up

TO-DO: Set up an example repo to showcase NEAR

### CODE REVIEW

**Comment by Nathan-Notifi** [comment]
overall looks good to me. is it possible to get a demo in this PR to make sure that the code there works?

**Comment by jennifer-notifi** [comment]
> overall looks good to me. is it possible to get a demo in this PR to make sure that the code there works?

Yes, working on a separate repo now.

**Comment by jennifer-notifi** [comment]
Please see the example: https://github.com/notifi-network/near-sdk-example

https://user-images.githubusercontent.com/108922885/208203701-640a5ee4-0ed4-4ae9-bbdc-2e9f03bf2975.mov

Verified that the code in this sample is the same as the code in this update.

I am digging into a potential bug on the client trying to grab the WalletPublicKey (which rotates) - this also should impact Aptos so I will check on Aptos and Near in a separate PR.

**Comment by jennifer-notifi** [comment]
Appropriate files: https://github.com/notifi-network/near-sdk-example/tree/master/src/Notifi

**Review by juni-notifi — APPROVED** [review]

**Pull request merged**
