### PR TITLE
Add new cosmos chains for BB

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by eric-notifi — COMMENTED** [review]
Just double confirm. I do not see these chains on our prod gql. 
Is it ready to merge?

**Review by eric-notifi — APPROVED** [review]
LGTM

**Comment by mayuranganesathas** [comment]
@jamie-notifi Added to this. On canary: 0.90.9-alpha.10

**Review by eric-notifi — CHANGES_REQUESTED** [review]
Seem it fails when build. Might want to have a look ( not on prod??)

**Review by eric-notifi — APPROVED** [review]
Looks awesome to me!!!

**Pull request merged**
